config/routes.rb
Friends::Application.routes.draw do
  devise_for :users
   devise_scope :user do
     root :to => 'homes#index'
   end

resources :friends, :controller => 'friendships' do
  get "requests", :on => :collection
  get "invites", :on => :collection
end

   root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:country,:state,:city,:zipcode
  # attr_accessible :title, :body
  geocoded_by :country
  after_validation :geocode, :if => :country_changed?
  
  include Amistad::FriendModel
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_filter :authenticate_user!

	  def index
	    @friends = current_user.friends
	  end

	  def new
	    @users = User.all :conditions => ["id != ?", current_user.id]
	  end

	  def create
	    invitee = User.find_by_id(params[:user_id])
	    if current_user.invite invitee
	      redirect_to new_friend_path, :notice => "Successfully invited friend!"
	    else
	      redirect_to new_friend_path, :notice => "Sorry! You can't invite that user!"
	    end
	  end

	  def update
	    inviter = User.find_by_id(params[:id])
	    if current_user.approve inviter
	      redirect_to new_friend_path, :notice => "Successfully confirmed friend!"
	    else
	      redirect_to new_friend_path, :notice => "Sorry! Could not confirm friend!"
	    end
	  end

	  def requests
	    @pending_requests = current_user.pending_invited_by
	  end

	  def invites
	    @pending_invites = current_user.pending_invited
	  end

	  def destroy
	    user = User.find_by_id(params[:id])
	    if current_user.remove_friendship user
	      redirect_to friends_path, :notice => "Successfully removed friend!"
	    else
	      redirect_to friends_path, :notice => "Sorry, couldn't remove friend!"
	    end
	  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	
		def index
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/friendships/index.html.erb
<h1>Listing Friends</h1>

<table>
  <tr>
    <th>Email</th>
    
  </tr>

<% @friends.each do |friend| %>
  <tr>
    <td><%= friend.email %></td>    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friend', new_friend_path %>

app/views/friendships/invites.html.erb
<% @pending_invites.each do |invites|%>

  <%= invites.email %> => 
  <%= link_to "Cancel invite?", friend_path(invites), :method => "delete" %>
<% end %>

app/views/friendships/new.html.erb
<ul>  
  <% @users.each do |user|%>
    <li>
      <% if current_user.friend_with? user %>
        <%= user.email %>
        |
        You are already friends!
      <% elsif current_user.invited? user %>
        <%= user.email %>
        |
        Pending request ...
      <% elsif user.invited? current_user %>
        <%= user.email %>
        |
        <%= link_to "Confirm friend?", friend_path(user), :method => "put" %>
      <% else %>
        <%= user.email %>
        |
        <%= link_to "Add friend?", friends_path(:user_id => user), :method => "post" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/friendships/requests.html.erb
<% @pending_requests.each do |request|%>  

  <%= request.email %> =>
  <%= link_to "Confirm friend?", friend_path(request), :method => "put"%>

<% end %>

app/views/homes/index.html.erb
Welcome  +++++++++++++++++++++++++=======================

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friends</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In', destroy_user_session_path, :method => :delete %> <br/><br/>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>